### ISSUE TITLE
VS2012 can hang on build with auto-cleanup and unsaved changes

### ISSUE THREAD

**Issue by codecadwallader** [codecadwallader/codemaid#1]
Transfer from Kevin Butler's [BitBucket 280](https://bitbucket.org/s_cadwallader/codemaid/issue/280/vs2012-hangs-on-build-with-auto-cleanup)

Visual Studio hangs when building(F6) if there are unsaved files. I have several pretty small files open in VS. I make changes to 1 or more files and hit F6 to build. More often than not, VS will freeze and I have to kill it from Task Manager. My save works so I don't lose work but it's annoying to have to keep restarting VS. I can see the spade window show "refreshing..." in the frozen VS screen. I'm running 0.7.0.2 beta in VS2012.

**Comment by FlouFlou** [comment]
Hi codecadwallader,
Thx for your amazing extension, I can't work without Spade since I installed it 6 years ago !
Took me a while but I discovered that I really have to uncheck "Load models asynchronously" because it took about 6-8 seconds to finish refreshing/loading when saving. It was just too annoying because I save my work very often. So unchecked this option was the solution.

**Comment by codecadwallader** [comment]
@FlouFlou Cool, I'm glad to hear that you've been enjoying it. :)  Also thanks for sharing that flipping that setting was helpful for you as it may be helpful for others.
