### ISSUE TITLE
CodeMaid treats commented out code as regular comments and makes it unusable after uncommenting

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#106]
Hi,

Minor, but really annoying issue. Sometimes during development it's needed to hide some pieces of code from execution. The straightforward way to do it — just comment them out. By whole blocks of methods or even classes.

But.

If developer runs `CodeMaid`'s cleanup to make rest of the code pretty the addon will re-arrange comments with code hidden in the. For example `CodeMaid` will run word-wrap on longer lines, and this will make code uncompilable when uncommented.

I think `CodeMaid` should check is this text comment or piece of code. And in case of last — preserve formatting.

**Comment by codecadwallader** [comment]
Detection of code vs. comment is challenging, so we follow some basic rules.  If there are two slashes, immediately followed by a character - we assume that is code when it comes to comment formatting.  If there are ever four slashes (StyleCop's recommended practice http://stylecop.soyuz5.com/SA1626.html) - we also assume that is code.

Wrapping should only be occurring if it is unable to detect the comment could potentially be code.

Can you provide a code sample that is formatting when you don't think it should?

**Comment by monze** [comment]
I have an example. Just created it, but we use this approach many places in our source code. We have some debug helping implementation in the code, that can be enabled to trace an error. As default it is comment out. The code is just created as test, and will not work, and serves only as example.

```
        /// <summary>
        /// Get the values of the xPath
        /// </summary>
        /// <param name="xmlDocument">The xmlDocument</param>
        /// <param name="xPath">The xpath path</param>
        /// <returns>The value, or string.Empty</returns>
        public static string GetValue(XmlDocument xmlDocument, string xPath)
        {
            string value = string.Empty;

            try
            {
                // Dummy code - does not work
                value = xmlDocument.ParseXpath(xPath).GetValue;
            }
            catch (Exception ex)
            {
                Debug.Fail(ex.Message, ex.ToString());
            }

            // The document is retrieved from the Internet. Save the document to d:, to debug why
            // the xPath failed, just uncomment the lines below.
            // string fileName = "D:/GetValueDocument.xml";
            // xmlDocument.Save(fileName);

            // return the value
            return value;
        }
```

The code as it is, is StyleCop valid, and we have some implementation, we can uncomment to help debug the situation.
```
            string fileName = "D:/GetValueDocument.xml";
            xmlDocument.Save(fileName);
```

This is just a short implementation, but could easy be several lines long, dependent of the situation.
If we enable automatic format comment, we end up with this:

```
            // The document is retrieved from the Internet. Save the document to d:, to debug why
            // the xPath failed, just uncomment the lines below. string fileName =
            // "D:/GetValueDocument.xml"; xmlDocument.Save(fileName);
```

Now we can't uncomment the lines, to make it works.
We use Visual Studio short-key crtl+k-crtl+c and crtl+k-crtl+u to comment and uncomment code.

Idea
Could there be an option, that indicate that only xml based comment should be formated, and not standard '//' comment?

I often write code comment like this:
```
        // You are at this point because of either
        //   1: You forgot to include a file.'
        //   2: The file was not a xml file
        //   2.1: The xml file has a wrong namespace
        //   3: The file was to big.
        // Identify why.
```

This structure will be 'destroyed' by any formation, which is undesired. It is perfect StyleCop valid.

Jacob Mogensen
mySupply ApS

**Comment by codecadwallader** [comment]
@monze Thanks for the code examples, that helps.

If you comment out code using the keyboard shortcuts, then there shouldn't be any leading space in front of the comment.  If there is not a leading space, then CodeMaid will assume it is code and not format that section.  The examples show a space between the comment and the code, making it really hard for CodeMaid to distinguish comment from code.  A second way you can indicate a commented out section is by following StyleCop's recommendation to double-comment code sections (i.e. press the keyboard shortcut twice to mark it with four slashes).  http://stylecop.soyuz5.com/SA1626.html  Either of these two approaches will help CodeMaid recognize a section as a code comment and skip it accordingly.

For the latter list scenario, I'd defer to @willemduncan but I think that may be a bug.  My best guess is that we don't have logic anticipating trailing lines after a list, which is why the "Identify why" gets wrapped onto the last line.

**Comment by monze** [comment]
Just a small comment .

I was very pleased, when I first found and tried CodeMaid. It works very well, and help to style the code in a nice way. But when I discovered, that from my point of view, it made total F***UP in my code comment, and I was total piss... 

However, I have now used CodeMaid for several months, and the more I thing about it, it does make sense. I like the auto-restructuring of the comment, just not when it is code comment. In the past, I always manually add an extra space after the first two forward slash (/), to make the code StyleCop valid, and after a CodeMade cleanUp many things is now structured wrong. So when CodeMaid restructure the code, in a undesirable way, it is very easy to blame the newest tool in the tool box, as the 'bad boy'. Why can't it just behave like I want it to...

As time goes by, I start to think, that it could be me, that was the 'bad boy', as I have written the comment in a wrong way. I like the styling of my written comment, just not when it was code. So instead of manually add the extra space to be StyleCop valid, I should have done this instead:
```
            // The document is retrieved from the Internet. Save the document to d:, to debug why
            // the xPath failed, just uncomment the lines below.
            ////string fileName = "D:/GetValueDocument.xml";
            ////xmlDocument.Save(fileName);
```
It is still StyleCop valid. 

I have ask my self this question: "Why most I add four slash to stop CodeMaid?"
The best answer I can give my self, is that the code actually consist of two different types of comment, and of course they can't use the same commenting style.  
* Two slash is written comment
* Three slash is xml comment
* Four slash is code

So, code that is comment out should always have four slashes.

Now the really good question is, how to make Visual Studio auto inset four slash when I use the short-cut 'ctrl+k-ctrl+c'. The only time I ever use this short-cut, is when I want to comment out some code.

Can CodeMaid chance this? It will prevent using wrong comment style in the future?

Jacob Mogensen

**Comment by willemduncan** [comment]
It's might not be perfect, but the simplest solution is to press the keyboard `ctrl+k-ctrl+c` shortcut twice.

The next problem we face is that a comment which contains any lines without leading spaces are always ignored when formatting. So attempting to format this will currently not work:
```
// The document is retrieved from the Internet. Save the document to d:, to debug why
// the xPath failed, just uncomment the lines below.
////string fileName = "D:/GetValueDocument.xml";
////xmlDocument.Save(fileName);
```

But if you separate the two parts like this it works fine:
```
// The document is retrieved from the Internet. Save the document to d:, to debug why
// the xPath failed, just uncomment the lines below.

////string fileName = "D:/GetValueDocument.xml";
////xmlDocument.Save(fileName);
```
I will try to update the "comment / code" detection to deal with this situation a bit smarter.

**Comment by willemduncan** [comment]
I looked into this a bit deeper, because I was sure we build a system that stops comment search expansion when the comment prefix changes, see ticket #26.

I updated that logic and moved the "require same prefix check" to before the "require initial space" check: This results in a much better flow which also fixes this issue, and you will now be able to format the comment part in a construction like this without problems:
```
// The document is retrieved from the Internet. Save the document to d:, to debug why
// the xPath failed, just uncomment the lines below.
////string fileName = "D:/GetValueDocument.xml";
////xmlDocument.Save(fileName);
```
