### ISSUE TITLE
Add Xamlr support

### ISSUE THREAD

**Issue by xperiandri** [codecadwallader/codemaid#121]
Could you add [Xamlr](https://visualstudiogallery.msdn.microsoft.com/4e0217da-264f-4e4e-b0f2-849fbad8e2af) ([2015](https://visualstudiogallery.msdn.microsoft.com/1d1bcc7b-b7b1-4386-bef6-fee8fb8a0ba5)) support?

**Comment by codecadwallader** [comment]
I'm not familiar with that tool.  Do you know if they expose their functionality through a Visual Studio command that can be invoked?

**Comment by xperiandri** [comment]
Yes.
Xamlr is an alternative to XamlStyler it binds to the same Ctrl+E,D

**Comment by codecadwallader** [comment]
I've peeked at their source code, and it appears they do not expose a command of their own - but they hook into the Visual Studio format document command so that when it is invoked, they are invoked.  Since CodeMaid invokes the Visual Studio format document command, I would guess that it may already be invoking Xamlr if it is installed as well.

If it isn't already working today, then I would suggest asking Xamlr to expose their functionality through a command that can be invoked by other tools.

Hope it helps.
