### ISSUE TITLE
Extra lines around single-line properties

### ISSUE THREAD

**Issue by dg9ngf** [codecadwallader/codemaid#129]
CodeMaid considers these multi-line properties and puts blank lines around each, as per my configuration:

    /// <summary>Description.</summary>
    public int SomeNumber { get; set; }
    /// <summary>Description.</summary>
    public int AnotherNumber { get; set; }

I consider these single-line properties and do not want blank lines around each, as per my configuration.

**Comment by dg9ngf** [comment]
It even considers the first of these as multi-line and the others as single-line:

    // Comment
    public int SomeNumber { get; set; }
    public int AnotherNumber { get; set; }
    public int MoreNumber { get; set; }
    public int AgainNumber { get; set; }

Result:

    // Comment
    public int SomeNumber { get; set; }

    public int AnotherNumber { get; set; }
    public int MoreNumber { get; set; }
    public int AgainNumber { get; set; }

**Comment by codecadwallader** [comment]
Correct, we consider leading comments to be part of a member.  This stems from reorganization, where if you wanted to move 'SomeNumber' you would expect the comments above it to come with it.

There isn't a way for CodeMaid to distinguish between a comment that is leading a set of fields, and that comment being for the first field since they look identical.  What I've done (see GuidList for example) is place a blank line after a comment that leads a group of fields/properties to distinguish it is not a comment for the first member.

**Comment by dg9ngf** [comment]
That extra blank line doesn't help a lot in the first described scenario. Lots of properties in a class, with only a single-line documentation to save space. I don't want more lines in those. There will be even less items fitting in one screen.

**Comment by codecadwallader** [comment]
Those lines are recognized as multi-line properties by design, so if you do not want blank line padding you will want to disable the associated option under Cleaning->Insert->Insert blank line padding before/after->multi-line properties.

**Comment by dg9ngf** [comment]
Could I ask for another option for single-line properties excluding comments then?

**Comment by codecadwallader** [comment]
Sure, new features can be requested on the Trello backlog here: https://trello.com/b/VVxVhbQv/backlog.

You could also create a custom version of CodeMaid by forking the code base, details on building the code here: http://www.codemaid.net/contribute/
