### ISSUE TITLE
Disable build progressing when BuildVision detected

### ISSUE THREAD

**Issue by davidruhmann** [codecadwallader/codemaid#149]
Request to have all of progressing automatically disabled when [BuildVision](https://github.com/nagits/BuildVision) is detected or at least an option to not override the user-specific progressing settings with the solution-specific progressing settings.

**Comment by codecadwallader** [comment]
It sounds like you have found the options that allow you to turn on/off CodeMaid's build progress indicators.  Solution-specific settings will always override user settings by design.  You can remove the progress options from your solution-specific configuration file if you do not want it to override user settings.

**Comment by davidruhmann** [comment]
The issue is when working on open source projects and loading their solution file and having to manually make sure to change it every time.  :thought_balloon: IMHO, there are some settings (like the progressing) that should not be solution specific because they have nothing to do with the code, but are developer specific with their environment.  CodeMaid to me does not provide enough benefit to deal with that.  Will just uninstall for now and if I have time fork and make a custom version.  Thanks for taking time to reply to my post.
