### ISSUE TITLE
Content between <summary> tags not separating from tags if ampersand (&) present in content.

### ISSUE THREAD

**Issue by kreddkrikk** [codecadwallader/codemaid#164]
I have this comment for a C# class declaration:

    /// <summary>
    /// All offset values below have been tested on Windows 7 & 8 only but you can use WinDbg "dt ntdll!_PEB" command and search for ProcessParameters offset to find the truth, depending on the OS version.
    /// </summary>

But doing a "Format Comment" action formats it to this:

    /// <summary> All offset values below have been tested on Windows 7 & 8 only but you can use
    /// WinDbg "dt ntdll!_PEB" command and search for ProcessParameters offset to find the truth,
    /// depending on the OS version. </summary>

The contents aren't on separate lines from the tags. However, after removing the ampersand (&) symbol it formats it correctly:

    /// <summary>
    /// All offset values below have been tested on Windows 7 8 only but you can use WinDbg "dt
    /// ntdll!_PEB" command and search for ProcessParameters offset to find the truth, depending on
    /// the OS version.
    /// </summary>

Other than this, CodeMaid is fantastic and works beautifully. Great job on this excellent add-on!

**Comment by Rychard** [comment]
This also occurs with <kbd><</kbd> and <kbd>></kbd>.  There may be other characters as well, but I just tested it with those.

However, if you use `&lt;`/`&gt;` (respectively), the issue does not occur.

As for the originally reported issue (regarding <kbd>&</kbd>), use `&amp;` instead.

I presume this occurs because the comments are XML, and the presence of these characters as text will result this XML becoming malformed.

**Comment by kreddkrikk** [comment]
That works, thanks!

**Comment by codecadwallader** [comment]
Excellent, thanks @Rychard for answering and you're correct - it is treated as XML.
