### ISSUE TITLE
Formatting/indenting of consecutive if statements in code blocks in .aspx files

### ISSUE THREAD

**Issue by rhelms** [codecadwallader/codemaid#165]
Hi

When a clean up is done of a .aspx file that has consecutive if statements where the if statement closes and reopens the code block, the indenting of the closing block for the inner if doesn't match the opening block.

For example, code that I might expect to be formatting like this:

```
<%
    var condition = true;
    var condition2 = true;
    var condition3 = true;
    if (condition)
    {
        if (condition2)
        {
%>
<p>Output here</p>
<%
        }
        else if (condition3)
        {
%>
<p>Output here also</p>
<%
        }
    }
%>
```

ends up looking like this:

```
<%
    var condition = true;
    var condition2 = true;
    var condition3 = true;
    if (condition)
    {
        if (condition2)
        {
%>
<p>Output here</p>
<%
    }
    else if (condition3)
    {
%>
<p>Output here also</p>
<%
        }
    }
%>
```

I'm not sure if that's a result of the break in the code block, and the closing block on the second if statement is led by the code block (1 indent from <%), rather than having the closing block match up with the open block, even if the code block closes and reopens.

I'm using VS 2015 Professional, and CodeMade v0.8.1.

If there is a way of allowing the brackets to line up, or have CodeMaid indent the <% appropriately, could you let me know? I've never been sure when <% should follow indenting the c# code, or the HTML of the .aspx, or both.

**Comment by codecadwallader** [comment]
The indentation of ASPX files is actually a native part of Visual Studio.  I believe you will see the same behavior if you invoke Edit->Advanced->Format Document.  CodeMaid invokes the native VS formatting, and then extends it with several other types of cleanups.

You could look under Tools->Options->Text Editor to see if there are any configuration options related to ASPX indentation.  My quick look did not see any.  You could also file an issue directly with Microsoft through the Send a smile/Send a frown icon in the top-right of VS2015.  I suspect they will say that it is expected behavior and they don't have support for indentation across separate code blocks.

**Comment by rhelms** [comment]
Thanks Steve.  I've sent my frown. I'll close this ticket, but if I hear anything back, I'll post it back here for others to see.

Your work on this extension is very much appreciated.

**Comment by codecadwallader** [comment]
That would be great, and thanks for that comment it is always very welcome to hear. :)

**Comment by Jackknifeexact90** [comment]
@rhelms https://laravel-7.github.io/3e2YhRzdNy7saR-OliUYhv8sOTmLcMmPrk2UKseDVkjt_JiwR4IYmQIGF6Dqv4ca7YLbvd5zd09h4oU2zhU/
