### ISSUE TITLE
Run format comments during cleanup inserts trailing space

### ISSUE THREAD

**Issue by TheCycoONE** [codecadwallader/codemaid#202]
Even when ```Remove end of line whitespace``` is enabled, ```Run format comments during cleanup``` causes a trailing space to be inserted on otherwise empty comment lines.

E.g. (using . to represent space)
```
///.<summary>
///.The following line is intentionally blank
///
///.Spiffy
///.</summary>
```
Becomes:
```
///.<summary>
///.The following line is intentionally blank
///.
///.Spiffy
///.</summary>
```
I would expect removing trailing white space to happen after and remove the trailing white space from the comment. This is needed to pass the default ```git diff --check```.

Using CodeMaid 0.9.0 on Visual Studio 2015. This is a C# project.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been able to reproduce it as well just by manually invoking comment formatting (i.e. it doesn't have to be tied to a cleanup session).

The comment formatting logic is the very last step applied in the cleanup process, so that is why the end of line whitespace is not otherwise caught.

I'll leave it to @willemduncan to look into it further.  Thanks again!

**Comment by kkm000** [comment]
I second that a comment formatting command adds trailing whitespace. Immediately noticeable with a trailing space highlighting plugin. :)

**Comment by codecadwallader** [comment]
As v0.9.1 is now released, closing this issue.
