### ISSUE TITLE
Hanging vs2015 while save C# file due to Spade refreshing

### ISSUE THREAD

**Issue by renkun-ken** [codecadwallader/codemaid#212]
When I save a C# code file, the Spade will automatically refresh but make VS2015 hang for a few seconds to reflect the up-to-date class structure. This is especially so when multi-threaded operation is enabled and much less significant if the option is disabled.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  We do as much work as possible on background threads to build up the model (see #208 for some more details) and virtualize the UI as well - but there is inevitably a moment where we need the UI thread in order to render the Spade visualization.

Some other information that would be helpful if you could provide it:
- CodeMaid version
- CodeMaid settings (user, solution as applicable)
- Code excerpt/file

I recommend not using the multi-threaded option (off by default).  It works well for some users, but I've heard more issues than successes so we are planning on removing it all together (https://trello.com/c/1WgXtP0i).

In the long term future, we do plan a rewrite based on the Roslyn code model which would allow us to do incremental updates to the model vs. rebuilding it on save.  https://trello.com/c/F8FFfNUd

**Comment by mezzodrinker** [comment]
CodeMaid version: 0.9.0
CodeMaid settings: [CodeMaid.config](https://github.com/codecadwallader/codemaid/files/114470/CodeMaid.config.txt)
Source file: [rev9.cs](https://github.com/codecadwallader/codemaid/files/114473/rev9.cs.txt)

I hope this additional information helps pinpointing the cause!

On a side note: by disabling multi-threaded operations, I can greatly reduce the performance impact as well.

**Comment by codecadwallader** [comment]
Thanks for the information, that's very helpful - especially the confirmation about multi-threading reducing performance.  I will pull that option ahead for removal in the next minor release (v0.9.1) so other people do not fall into that as well.

**Comment by codecadwallader** [comment]
I've confirmed the hang when multi-threaded operations are enabled, so again we will absolutely remove that option as discussed above.

When I disable that option, I'm only seeing some sub-second interruptions while the UI painting occurs.  The majority of the refresh time (i.e. when the pane is grayed out and says "Refreshing...") runs on background threads and you should be able to interact with the IDE as normal.  It's the final moment when the UI is re-rendering that does require a UI interruption.  It looks like we currently have that running at an input priority level, so I will reduce that to a background priority level.  This should cause it to wait a little longer if the user is in the middle of an input operation (e.g. typing in the editor) before it paints so that UI thread interruption will hopefully be less noticeable.

**Comment by rainbowdesign** [comment]
Is there a way to disable the spade refresh on saving the file (so i only manually refresh it then) it takes normally quite some seconds to refresh it. so there should be an option.

**Comment by codecadwallader** [comment]
There isn't currently an option for it, but it would be a pretty easy one to add.  New feature requests are  accepted/captured on Trello here: https://trello.com/b/VVxVhbQv/backlog

**Comment by rainbowdesign** [comment]
I signed up for it but i dont see how to create a new request....

**Comment by codecadwallader** [comment]
The first card in the top left says "You can add comments on this card to request new cards to be created.": https://trello.com/c/1IQl1f7t

**Comment by codecadwallader** [comment]
This fix is now available in the latest beta here: https://github.com/codecadwallader/codemaid/releases/tag/v0.9.0.2-beta

If anyone has a chance to test and confirm the fix it would be greatly appreciated.  If there are any issues please comment and we'll reopen the issue.
