### ISSUE TITLE
On save codemaid spade extends all

### ISSUE THREAD

**Issue by rainbowdesign** [codecadwallader/codemaid#219]
When i save a file the codemaid spade opens all regions (regions, classes functions...) even such that were collapsed before and such that collapsed in visual studio.

Expected behavior would be either to keep the state as it was before saving collapsed / extendet 
Or to fit it to the state of the region in visual studio

This is just annoying because every time i save my project i have to collapse all my classes in the spade again.

**Comment by codecadwallader** [comment]
Sorry to hear it's not working as expected.  The default behavior is for Spade to respect and synchronize outlining state with the file.  So for example when you collapse a region in the code editor, it collapses within Spade - and vice versa.  Since that state is synchronized with the code editor, as long as the code editor maintains its state, then Spade should as well after a refresh.

Some of the following information would be helpful if you can provide it:
- Visual Studio version
- CodeMaid version
- Project language (e.g. C#, C++, VB)

**Comment by rainbowdesign** [comment]
vs community 2015 14.0.24720.00
codemaid 0.9.0
c#

oh yes i tryed with the settings i tried to find a way to insert a comment (now i use regions for this)
and disabled the syncronisation...
So it just behaves like this when its not syncronized.

**Comment by codecadwallader** [comment]
Thanks for the information.  So it sounds like the outlining synchronization is working as expected and maintains the expand/collapse state as designed when that option is enabled (and it is enabled by default).  Is there anything further for this issue or shall we close it?

**Comment by rainbowdesign** [comment]
Indeed i think its not important enough so i close it.
