### ISSUE TITLE
Solution Explorer: Option to Show/Hide CodeMAID Buttons

### ISSUE THREAD

**Issue by kgallaha** [codecadwallader/codemaid#266]
**Split from #259**

This is a feature request to provide a new setting to appear in the General section or split between Cleaning->General and Collapsing.

Toggling the setting(s) would simple show or hide the CodeMAID clean and collapse buttons which are automatically added to Visual Studio's Solution Explorer.

**Comment by codecadwallader** [comment]
Thanks for splitting this out!  Those buttons were originally added back in VS2005 days and now that VS has a built in collapse button they're not as useful.  I tried taking them away once before and actually got a number of user complaints, so put them back in quickly.  Looking back through the archives that was back at v0.7.3 and it was specifically VS2010 users since the collapse button doesn't exist for VS2010.  We no longer support VS2010 these days, so I'm inclined to just take the buttons away all together vs. having more configuration options (we already have 141).  Thoughts?

**Comment by kgallaha** [comment]
I'd be fine with just removing them since the same options are available from context menus which are simpler to bring up than going to the SE toolbar (no other extensions that I've installed have put buttons on it).

I imagine some users might still be in the habit of clicking on them though which is why I suggested a show/hide setting.

**Comment by codecadwallader** [comment]
Cool, appreciate the input.

**Comment by codecadwallader** [comment]
The buttons have been removed, will be present in the next release.
