### ISSUE TITLE
Nested regions reorganization

### ISSUE THREAD

**Issue by khorvat** [codecadwallader/codemaid#281]
### Environment
- Visual Studio version: 2013 Premium U5
- CodeMaid version: 10.0.88
- Code language: C#

### Description
I just want to be sure what to expect from nested region reorganization so can you confirm if my custom regions inside the method should be removed in reorganization process in case where I have "Remove regions ..." turned on ?

### Current behavior
Custom nested regions are removed.

### Expected behavior
For some reason I though CodeMaid will leave my regions alone. I understand that this is maybe an odd expectation having "Remove regions ..." on.

**Comment by codecadwallader** [comment]
When "Remove regions" by itself is enabled, we do the following:

- Retrieve all existing regions
- Determine which regions need to be present because they have a member that requires them (e.g. #region Methods if a method is present)
- Remove all other regions

Here's a link to the relevant code which probably explains it better than any other words: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/GenerateRegionLogic.cs#L72

This logic is repeatedly used across the code hierarchy and has explicit handling to make sure nested regions are removed as well: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/CodeReorganizationManager.cs#L411

So yes, the expected behavior is that all custom regions are removed if "Remove regions" is enabled.  Hope it helps.

**Comment by khorvat** [comment]
Yes, thanks .. .will review other replies.
