### ISSUE TITLE
Cleanup All Code & Collapse All Recursively missing in Solution Explorer top bar

### ISSUE THREAD

**Issue by wouterroos** [codecadwallader/codemaid#289]
### Environment
- Visual Studio version: 2015 Enterprise Update 2
- CodeMaid version: 10.1.93
- Code language: C#

### Description
Since installing Update 2 the options to Cleanup All Code * Collapse All Recursively have dissapeared from the solution explorer (see image). The options are however still present in the right-click menu.

![image](https://cloud.githubusercontent.com/assets/5137829/15143784/c281c2c2-16ab-11e6-9eb0-03916f546b10.png)

### Steps to recreate
1. Install Update 2 
2. Open Solution Explorer

### Current behavior
Cleanup All Code * Collapse All Recursively are not visible in Solution Explorer

### Expected behavior
Cleanup All Code * Collapse All Recursively are visible in Solution Explorer

**Comment by codecadwallader** [comment]
Those buttons were deliberately removed as part of the v10.1 release (see #266 or http://www.codemaid.net/2016/04/23/codemaid-v10-1-keep-rolling-edition-released/#comments). The collapse option was originally added back in the VS2005 days, but since VS2012 there’s already been a native button present that has the same functionality. Look for the three squares with a minus sign on it. Hope it helps!

**Comment by wouterroos** [comment]
Ah thanks for clearing that up. I must have upgraded at around the same time as update 2 for Visual Studio.

**Comment by codecadwallader** [comment]
No problem, sorry for any confusion.
