### ISSUE TITLE
Find in solution explorer fails in Spanish

### ISSUE THREAD

**Issue by raullorca** [codecadwallader/codemaid#31]
Hi guys,

When I call - Find in solution explorer - error HRESULT E_FAIL a call appears in a COM component. 
I have reinstalled (first I uninstalled) and the same thing keeps happening. 
I use VS 2013 Ultimate Update 3 in Spanish 
Can you help?

Thanks.

**Comment by codecadwallader** [comment]
Microsoft provided an alternate way to invoke the command that should allow it to work for Spanish versions.  I have implemented that alternative and it will be present in the next beta release.

I would appreciate help in testing this change out once the beta is release since I am unable to reproduce the issue.

**Comment by MikelLuri** [comment]
Sure, I'll test it! How can I get the beta version when it's out?
Thanks!

2015-02-14 14:40 GMT+01:00 Steve Cadwallader <notifications@github.com>:

**Comment by codecadwallader** [comment]
Great, thanks.  It will be available here on GitHub when it is published.  I'll post an update to this thread with a link.

**Comment by codecadwallader** [comment]
This is being published in the new v0.7.6 release, it should show up in Visual Studio for you automatically soon.  If there's any outstanding issues, please comment here accordingly!

**Comment by MikelLuri** [comment]
It works fine now, thanks!

**Comment by codecadwallader** [comment]
Wonderful, thanks for confirming! :)
