### ISSUE TITLE
More Spade parameters

### ISSUE THREAD

**Issue by FlouFlou** [codecadwallader/codemaid#321]
### Environment
- Visual Studio 2012
- CodeMaid 10.1
- C#

I create an issue, like codecadwallader asked me. Sorry for the fake pull requests Steve. I understand how it works now.

The Spade tool is very important to me. Steve gave me quick responses but i would write my questions as an issue. Maybe someone could help me.

- Is there a way to show only public properties (because i use a lot of mvvminpc properties) / methods / **region in methods** ? (maybe with a !suffix / suffix or the key word private)
- - quick response : no
- Is there a way to Spade to keep the collapse/expand the way i leave it ? Because it's annoying when i do some code or switch to en other file and then Spade reload the entire structure and expand all. 
- - quick response : yes (default). So what it's happening ? Some VS 2012 options ?
- In this previous example, if i click to many times during the refresh, VS 2012 can freeze. I have to reboot the solution. I'm pretty sure it's CodeMaid fault because the Spade window seems to do some infinite loop or something and i think VS is waiting for it.
- - quick response : try resetting to default settings (known issue if you override some 'skip' options in VS2012). What are these 'skip' options ?
- Also the auto refresh (synchronize outlining with the code file) doesn't work as expected. I have to manually "Refresh Spade" when i add/update/delete something. Ctrl+s works fine.

**Comment by codecadwallader** [comment]
Thanks for moving this into an issue, and no problem at all about the pull request. :)

> Is there a way to Spade to keep the collapse/expand the way i leave it ? Because it's annoying when i do some code or switch to en other file and then Spade reload the entire structure and expand all.
By default we synchronize the expand/collapse state with the code outlining, so when you collapse a region in code it collapses within Spade.  You can confirm this setting is enabled at CodeMaid->Options->Digging (Spade)->"Synchronize outlining with the code file"

> In this previous example, if i click to many times during the refresh, VS 2012 can freeze. I have to reboot the solution. I'm pretty sure it's CodeMaid fault because the Spade window seems to do some infinite loop or something and i think VS is waiting for it.
Please be sure that skip settings that are on by default are still enabled.  They can be found at CodeMaid->Options->Cleaning->Visual Studio->"Skip during automatic cleanup on save" [2 different settings, one under remove usings and one under sort usings) as well as under CodeMaid->Options->General->"Skip during automatic cleanup on save"

> Also the auto refresh (synchronize outlining with the code file) doesn't work as expected. I have to manually "Refresh Spade" when i add/update/delete something. Ctrl+s works fine.
This is the known and expected behavior of Spade.  It does not attempt to live update as the code file changes, but only upon document open/save or a manual refresh.  When we convert to the newer Roslyn compiler (VS2015 only) we will have access to a newer API that will enable us to add live model refreshes.  The synchronize outlining feature you mentioned is to match the expand/collapse states between Spade and the code file (e.g. collapse a region within the code file and it collapses within Spade).

I hope those answers help with some of your questions.  If you have any more questions please just continue the thread here and I'll get a notification. :)

**Comment by FlouFlou** [comment]
Thx for reply

It seems that i had to enable also "Outlining" in VS 2012->Tools->Text Editor->Outlining ("Mode Plan" in French... unbelievable :( ). Actually you're right the expand/collapse state is synchronize with code outlining, so it's just perfect :) !

I disabled CodeMaid->Options->Digging (Spade)->"Synchronize outlining with the code file" in the past because i believed that it might be a cause for point 3 (freeze). I re enable it and it seems to work as expected.

Also no freeze for the moment

**Comment by codecadwallader** [comment]
Cool, thanks for following up and glad to hear it is helping.  I'll go ahead and close this issue for now, but if you have further questions just go ahead and comment again and I'll still get a notification.  Enjoy!
