### ISSUE TITLE
Option to replace explicit declarations to implicit

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#324]
I was thinking, is it possible to add experimental feature to convert explicit declarations to implicit ones?

All these:

```c#
Dictionary<string, VerySpecificAndLongClassName> myDictionary = new Dictionary<string, VerySpecificAndLongClassName>()
```

turn into these automatically:

```c#
var myDictionary = new Dictionary<string, VerySpecificAndLongClassName>()
```

Sometimes developer could use these verbose declarations during beginning of development for example to clearly indicate for team members which variable type is expected here. And often these declarations end up in production code as well. But it's hard to read and always painful to get rid off.. It would be nice if this could be done automatically or semi-automatically.

This functionality could be disabled by default, so people will not spoil their code unintentionally (I think it could be problems if `dynamic` objects are used, but we can also detect such cases)

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I know ReSharper already has this feature and it also looks like Microsoft is adding this natively in VS15: https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes#cshappvb .  Since it will be in the next major release of VS, I don't think we'll plan on implementing it in CodeMaid - but certainly appreciate the idea and agree it will be nice to have. :)
