### ISSUE TITLE
Automatic Cleanup on Save not working on VS 2017 RC

### ISSUE THREAD

**Issue by eduardocp** [codecadwallader/codemaid#375]
### Environment
- Visual Studio version: 2017 RC Enterprise
- CodeMaid version: 10.2
- Code language: C#

### Description
With Automatic cleanup on save active, unnecessary usings aren't being removed

### Steps to recreate
1. Create new file or open one
2. Add some unnecessary usings
3. Save the document

### Current behavior
The unnecessary usings remain

### Expected behavior
The unnecessary usings should be removed

**Comment by codecadwallader** [comment]
Thanks for reporting the issue and for helping to test out the new VS2017 support!

By default, we do not remove using statements during automatic cleanup on save.  The reason for this is that it would cause some infinite loops in older versions of Visual Studio and result in the IDE hanging.  It didn't do this for everybody, but we play it safe by default.

You can override this behavior at CodeMaid->Options->Cleaning->Visual Studio->"Skip during automatic cleanup on save" which is on by default.

Note:  The name of these options changed with the VS2017 updates since Microsoft merged the underlying separate Remove and Sort commands together into a single command.  So if you previously had this option set, it would have been reset to the default setting when you upgraded to 10.2

Hope it helps and please let us know if you see anything else!
