### ISSUE TITLE
Incorrect formatting for css @supports

### ISSUE THREAD

**Issue by buzzin0609** [codecadwallader/codemaid#432]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: 10.3
- Code language: css

### Description
When using the css @supports feature, CodeMaid incorrectly formats the block when doing a clean up or reformat. E.g. 

```` 
@supports (pointer-events: none) {
        display: block;
        pointer-events: none;
    }
````

is formatted to:

````
@supports 

(pointer-events: none) {
        display: block;
        pointer-events: none;
    }
````

### Steps to recreate
1. Add any rule inside @supports (property: value) { }
2. Choose Cleanup Active Document from CodeMaid menu

### Current behavior
From guessing, it looks like CodeMaid simply doesn't recognise the syntax, so formats it incorrectly?

### Expected behavior
Should keep the @supports and the following braces together when formatting

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been unable to reproduce it.  Can you try the following?

1.  On that file invoke Edit->Advanced->Format Document.  Visual Studio has a lot of native formatting capabilities that we invoke as a starting point for our own clean ups.  We don't have any specific rules related to the scenario you described so I suspect that is a native formatting issue.

2.  Try creating a minimal solution with default settings that exhibits the issue.  Frequently issues are related to specific setting configurations or specific code elements and isolating them can help point to a root cause.

Hope it helps.

**Comment by buzzin0609** [comment]
Hi, thank you for getting back to me.

You're right, it seems to be a native formatting issue as the same thing happened after using the Format Document command from the edit menu.

Is there a way to add an exclude to this using CodeMaid or do I need to send a bug report to Microsoft?

**Comment by codecadwallader** [comment]
You can disable our invocation of the native formatting (CodeMaid->Options->Cleaning->Visual Studio->Run format document) but you'll lose all other formatting completed by that command.  It is handling most of the indentation, argument spacing and operator spacing aspects.

If there are any relevant native configuration options, they would be under Tools->Options->Text Editor->CSS.  I see an option under Advanced for "Brace positions" which you could experiment with modifying.

Reporting a bug to Microsoft is indeed the best approach to get it resolved long term.  There are feedback tools built into VS now (see top right corner) that make this a lot simpler than it used to be.

**Comment by buzzin0609** [comment]
Thank you! :)

**Comment by codecadwallader** [comment]
Glad to help, thanks for being polite. :)
