### ISSUE TITLE
Codemaid does not load solution settings

### ISSUE THREAD

**Issue by mberaz** [codecadwallader/codemaid#557]
### Environment
- Visual Studio version: [example 2017 professional 15.7.1]
- CodeMaid version: [example 10.4]
- Code language: [example C#]

### Description
Codemaid does not load solution settings on the Visual Studio load, i have to manually change something in the settings for them to apply,

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I am unable to reproduce it.  CodeMaid has solution specific settings and it is working by both primary solution load paths:

a.  Open Visual Studio, then open the solution.
b.  Double click the solution from the file explorer, which loads Visual Studio and immediately the selected solution.

A couple things to checks:

1.  Check that your CodeMaid.config file is in the same folder as the .sln file.  The solution directory is where we look for a solution settings configuration file.
2.  Pull down CodeMaid and see if it opens solution-specific settings for you.  The easiest way to confirm if solution-specific settings are loaded is to open the CodeMaid Options window and the banner across the top will either say "User Settings" or "Solution-Specific Settings" based on which is loaded.

Hope it helps.

**Comment by codecadwallader** [comment]
Strange, I'm using the latest mainstream build (v15.7.2), what version are you using?

**Comment by Sango2k** [comment]
Hi, I am having the same issue.
I just updated VS2017 to the latest version 15.7.2.
Steps to reproduce: (Make sure user specific settings are set to default)
1. Create new c# console app project
2. Go to CodeMaid -> Options -> Switch to solution specific version -> General -> Enable "Automatically run cleanup on file save" -> Press "Save"
3. Restart Visual Studio
4. No cleaning is performed on file save(the option in CodeMaid->"Automatic Cleanup on Save" is disabled)

It just totally ignores the solution specific settings, this worked fine in previous version of VS.
Note: The file CodeMaid.config exists in the same folder as the solution as expected.
This is really annoying because we not using CodeMaid on some of our solutions so I dont want to use "User" specific settings.

**Comment by codecadwallader** [comment]
Thank you for walking through the steps.  I went through those as well, and it is working as expected for me (i.e. at Step 4 - cleaning IS performing on file save).

I am running the latest CI build (looking to do an official release soon).. could you try repeating the steps with this latest version of CodeMaid and see if you're still seeing the problem?

http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/

**Comment by Sango2k** [comment]
Sorry, forgot to update, but I can confirm that with the latest version it works as expected!
Thanks!

**Comment by codecadwallader** [comment]
Glad to hear it, thanks for confirming. :)
