### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by kellcomnet2** [codecadwallader/codemaid#603]
### Environment
- Visual Studio version: [2019 Professional]
- CodeMaid version: Any
- Code language: Any

### Description
Add support for Visual Studio 2019

### Steps to recreate
1. Try to add Codemaid to VS 2019
2. You can't

### Current behavior
You can't

### Expected behavior
You can

**Comment by ShaharPrishMSFT** [comment]
Only thing really blocking me from moving to VS2019... :)

**Comment by codecadwallader** [comment]
Looks like someone went ahead and updated the manifest file and submitted #604 - awesome!  The CI channel has crunched it out and it can be found here: http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/  It installed for me and I was able to run basic cleaning/digging/organizing command as expected 😎 

There will be a warning banner at the top about "risk of not functioning in a future VS update".  This is because we're still backwards supporting VS2012/VS2013 and we'll have to drop those in order to switch to some alternate APIs.  It should(tm) still work for now, enjoy!
