### ISSUE TITLE
Reorganize Code option is disable for some files.

### ISSUE THREAD

**Issue by slo415** [codecadwallader/codemaid#61]
I noticed that for some files, Reorganize Code option is disabled. So I could not reorganize the code. I cannot even find why it is disabled in documentation. Attachment is the screenshot for reference.
![Screenshot](https://cloud.githubusercontent.com/assets/10415304/5626410/e41a13c0-95c5-11e4-920f-54386f4f7dff.jpg)

**Comment by codecadwallader** [comment]
One of the common causes is if the file is not a part of the solution but is just a file that you opened in Visual Studio.  In that case, there is no code model to work with so reorganization cannot run.  Can you confirm the file was a part of the solution?

**Comment by codecadwallader** [comment]
I took a second look at this screen shot, and noticed that it contains preprocessor directives within the file.  Since those can significantly alter the meaning of the file, one of the popular requests in the past was to disable reorganization for any file that contained preprocessor directives. https://trello.com/c/Qqd0GLqI

Although it isn't ideal, a workaround would be to temporarily remove the preprocessor code section from the file, perform reorganization, then re-insert it where you want it to exist.

**Comment by slo415** [comment]
Thanks you for your comment. I am new to CodeMaid and I could not able to find it in documentation of CodeMaid. I understand your point and appreciated for the answer.

**Comment by codecadwallader** [comment]
You're welcome, and thanks for sharing your experience - I will consider extending the diagnostic logging to include more details about when an operation is disabled.
