### ISSUE TITLE
'CodeMaidPackage' package did not load correctly message on VS 2017 start

### ISSUE THREAD

**Issue by AnotherOneIs** [codecadwallader/codemaid#634]
### Environment
- Visual Studio version: VS Professional 2017 15.7.5
- CodeMaid version: 11.0.183
- Code language: C++
- .Net version 4.7.03062

### Description
Opening a solution gets this box:
![image](https://user-images.githubusercontent.com/48922062/54936905-5f1da380-4f1b-11e9-8fc4-297cf0e88851.png)
The 'CodeMaidPackage' package did not load correctly.

### Steps to recreate
1. Open a VS solution 

### Current behavior
CodeMaid not accessible. I've been using it successfully for some years.
I looked in the ActivityLog.xml file that the dialog refers to but it didn't mean much to me!

![image](https://user-images.githubusercontent.com/48922062/54937757-ec152c80-4f1c-11e9-9883-7bb4108dcb4f.png)

### Expected behavior
It should be accessible after VS starts.

**Comment by alfredorevilla** [comment]
I'm experiencing the same. Out of nowhere it began to fail. Neither restart or extension reinstall helps.

**Comment by keithejc** [comment]
Same here - I uninstalled then installed version 10.6:
 https://github.com/codecadwallader/codemaid/releases

Then in `Tools/ Extensions and Updates`, unticked `Automatically update this extension`

**Comment by AnotherOneIs** [comment]
> Same here - I uninstalled then installed version 10.6:
> https://github.com/codecadwallader/codemaid/releases
> Then in Tools/ Extensions and Updates, unticked Automatically update this extension

That sorted it. Thank you keithejc!

**Comment by AnotherOneIs** [comment]
There is still an issue with 11.0.183

**Comment by attrib75** [comment]
Same here.  After the update, under the CodeMaid menu in VS, the only options are 'options' and 'about'.  Neither of which do anythying

**Comment by codecadwallader** [comment]
Thanks for reporting the issue all.  We had some significant changes in v11 to fully support VS2019 (more details here: http://www.codemaid.net/2019/03/23/codemaid-v11-0-vs2019-async-load-edition-released/ ) including some breaking changes.  I suspect this is the root of the issue.

Two questions (this is answered by OP, but I'm offering for others as well):
1.  What version of .NET Framework is installed?  v4.7.2 is the new target framework.
2.  What version of VS2017 is installed?  v15.8 is the new target API set.

If it's possible to upgrade to those versions of .NET and VS I believe that will address the issues seen above.  If anyone is seeing otherwise, please let me know.

If it's not possible to upgrade to those versions (e.g. corporate environment), as a workaround yes going back to CodeMaid v10.6 will certainly work since v11 is what introduced these higher requirements.

I was hoping that the manifest requirement rules would be enforced at upgrade time (not just first install time) but I think that may not be the case.  I also think I made a mistake in the manifest where it does not require v15.8 just v15.x and will look to update that.  I'm sorry for the trouble/confusion that the upgrade has caused and hope this explanation helps!

@attrib75 I think you are seeing something separate which is as designed.  Until you open a solution most menu items are not applicable (except for options and about).  If you're still seeing that issue after you open a solution and after you wait a moment (packages are loaded asynchronously now so there may be a moment's delay while the IDE catches up) please open a separate issue.

**Comment by AnotherOneIs** [comment]
Thank you for looking into this.
Unfortunately, I am unable to upgrade to the required versions of .NET and VS just yet, so I can't confirm anything to help out. Hopefully, others can do so.
Just for the record, my setup behaved the same way as reported by @attrib75 when I opened a solution.

**Comment by attrib75** [comment]
Hi, thanks for responding.  I can confirm that upgrading to VS 15.9.10 fixes this.

**Comment by AnotherOneIs** [comment]
I have upgraded to VS 15.9.10 and re-installed CodeMaid 11.0.183 - all good now, thanks for the support (and the useful tool).

**Comment by codecadwallader** [comment]
Great, thank you both for confirming!

**Comment by dontbyte** [comment]
Unfortunately I'm experiencing the same error with VS 16.8.4 and CodeMaid V12.0 again.
CodeMaid V11.2.231 works fine.

**Comment by APA-SLnk** [comment]
> Unfortunately I'm experiencing the same error with VS 16.8.4 and CodeMaid V12.0 again. 

The same ... VS16 and CodeMaid 12.0.
I didn't try with v11.2.231 since I have no idea where to get it.

**Comment by CliffAshby** [comment]
Updating Visual Studio 2019 to the most recent update (version 16.11.6) fixed the problem for me.

**Comment by codecadwallader** [comment]
Thanks @CliffAshby for the proposed fix (upgrade VS2019 to latest).  I'll be interested to hear if that helps for others.

**Comment by jarukitppg** [comment]
Mine is also on 16.8.4 and getting the same error, but upgrade to 16.11.6 as Cliff said solved the issue.

**Comment by codecadwallader** [comment]
Cool, thanks for confirming @jarukitppg .  There were several other reports on #865 as well that confirmed upgrading VS alongside upgrading CodeMaid resolved the issue. :+1:

**Comment by Ashley-alex** [comment]
Yes VS upgrade resolved the issue

**Comment by harry-chin** [comment]
My VS2019 was 16.9.4 and had an issue with CodeMaid 12.0, but after upgrade to 16.11.16, the issue has gone.
