### ISSUE TITLE
Removing unnecessary using's not working in VS2019

### ISSUE THREAD

**Issue by eddynaka** [codecadwallader/codemaid#648]
### Environment
- Visual Studio version: 2019 Enterprise
- CodeMaid version: 11
- Code language: C#, WebApi, .Net Core 2.1

### Description
Removing using statement that are not being used

### Steps to recreate
![image](https://user-images.githubusercontent.com/16199012/56826174-e53a4c00-6831-11e9-830f-bc6f5770556d.png)

![image](https://user-images.githubusercontent.com/16199012/56826144-ccca3180-6831-11e9-9fc9-89797989cc58.png)

![image](https://user-images.githubusercontent.com/16199012/56826124-b7ed9e00-6831-11e9-8cf3-c09488c41d5c.png)

### Current behavior
The current version in VS2019 isn't ordering / removing unnecessary using's

### Expected behavior
When the document is saved (if the option is enabled), it should remove unnecessary using's.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  When the sub-option "Skip during automatic cleanup on save" is enabled it will NOT run when triggered by a save event.  This option is designed for a few different scenarios including compatibility with other extensions, working on a file in progress and not wanting the using statements to be removed until completed, etc.  If I read the report correctly I think you want to deselect that option so that it will remove unnecessary using statements even when triggered by automatic cleanup on save.  Does that help?

**Comment by eddynaka** [comment]
thanks! that was the case
