### ISSUE TITLE
CodeMaid 0.7.5 "CodeMaid stopped cleaning" 0x80004005 VS 2013 Update 4

### ISSUE THREAD

**Issue by ToddShelton** [codecadwallader/codemaid#71]
This is random behavior on C# project files.  Usually they work, but when this error happens it's like the file itself is broken.  Sometimes recreating the file works, other times not.  Files that clean still clean, and files that won't clean won't.  Thsi error appears on two different Here's the error: 

`
[CodeMaid Handled Exception 08:24:26 PM] Stopped cleaning 'IOrderOld.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.SortUsingStatements(Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClassb.<Cleanup>b__9()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)
`

**Comment by codecadwallader** [comment]
The key line in that excerpt is SortUsingStatements which indicates that Visual Studio isn't in a state where it can clean a file.  Does this happen when you are running a build?  If you invoke a manual cleanup, does this still occur?

Can you provide a sample file that exhibits the issue?

**Comment by ToddShelton** [comment]
Turns out that after a fairly big refactor there were (more than) a few nits that created some strange build/non-build behavior.  Intellisense stopped working too, in some cases.  Once I went through the code with a fine-toothed comb and got a truly clean build CodeMaid worked properly again, and on the problematic files without changing them.  

Doesn't seem to be a file-specific issue, rather CodeMaid seems to be responding to the solution's buildable state.  Make any sense?

**Comment by codecadwallader** [comment]
Yes, part of cleanup activities is to request a code model from the VS API.   If the code is in a bad state, then that code model can be incomplete and will reduce the number of cleanup actions that can be taken.  The VS SortUsingStatements command not running makes sense in that context because it can't analyze the needed using statements.

**Comment by ToddShelton** [comment]
Oh, so if I turned off sort usings it might run?  Of course clean code is a lot better, but that ctrl-M-space is like straightening up.  Especially useful when doing those big messy refactors where code state goes wonk for a while.

**Comment by codecadwallader** [comment]
It depends on the state of the code on what code model will be returned, and that drives what operations can occur.  For example if it can't recognize that there is a method at line 20 because there's a missing semicolon at line 15, then blank line padding for that method won't be able to operate.  The same situation applies for VS commands (sort/remove) usings as well.  Does that help/make sense?

**Comment by ToddShelton** [comment]
It does, both, thanks.  I sure appreciate your work on this tool.

**Comment by codecadwallader** [comment]
Cool, and I enjoy doing it thanks for the appreciation. :)
