### ISSUE TITLE
CodeMaid 11.1.209 crashes VS2019 when trying to change the default font

### ISSUE THREAD

**Issue by RHWoodman** [codecadwallader/codemaid#765]
### Environment
- Visual Studio version: [Visual Studio Community 2019, version 16.8.3]
- CodeMaid version: [example 11.1.209]
- Code language: [N/A (this happened with no code being used)]

### Description
I opened Visual Studio 2019 using the "Continue without code" option. I went to the CodeMaid options --> General and tried to change the default font from Segoe UI. Apart from a high amount of disk activity, nothing happened for several seconds, then VS crashed and restarted. Upon restart, VS informed me that CodeMaid caused the crash and asked me if I wanted to disable the extension. I repeated this exercise three times with the same results.

### Steps to recreate
1. Open VS2019.
2. At the opening screen, select "Continue without code -->"
3. When VS2019 finishes loading, go to Extensions --> CodeMaid --> Options to bring up the CodeMaid options screen.
4. Under the "General" user settings, click on the font option and try to change the default font to something else.
![2020-12-29_VS2019_CodeMaid_Options](https://user-images.githubusercontent.com/2689861/103326280-989f0f00-4a1d-11eb-9145-6807080e59be.PNG)

![2020-12-29_VS2019_Restart-after-CodeMaid-Crash](https://user-images.githubusercontent.com/2689861/103326289-ace30c00-4a1d-11eb-8e68-9e5695f93fa5.PNG)

### Current behavior
Crashing Visual Studio when trying to change the default font is not expected behavior.

### Expected behavior
I should be able to change the default font without crashing Visual Studio.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been unable to reproduce it, but I suspect the issue is very specific to the fonts present on the system.

We utilize a general drop down that pulls a list of fonts from the system using a native WPF capability:

https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-enumerate-system-fonts?view=netframeworkdesktop-4.8

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/UI/Dialogs/Options/General/GeneralDataTemplate.xaml#L33

I suspect there is a font on your system that is unable to render, or there is a large number of fonts and it is taking too long to load them all into memory.

As a workaround, the configuration file can be directly modified with a text editor instead of using the drop down picker.  For user settings (default) the file is typically located at `C:\Users\{YourName}\AppData\Local\CodeMaid\CodeMaid.config`.  For solution-specific settings the file is located in the same folder as the `.sln` file.

**Comment by RHWoodman** [comment]
Thanks for the quick response. I do indeed have many fonts accumulated over many years, so it could that there are too many of them or that one of them is not loadable.

In modifying the XML configuration file, do I take the code section to which you pointed me, add that code under User Settings in the config file, and change the source to _static fonts.{name of specific font}_ that I want to use? (My eyesight isn't great, and I want to change SegoeUI to Verdana, which is easier for me to read.)

**Comment by codecadwallader** [comment]
Here's an example config file with Verdana set:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="SteveCadwallader.CodeMaid.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <SteveCadwallader.CodeMaid.Properties.Settings>
            <setting name="General_Font" serializeAs="String">
                <value>Verdana</value>
            </setting>
        </SteveCadwallader.CodeMaid.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by RHWoodman** [comment]
Thank you!

**Comment by codecadwallader** [comment]
Happy to help. :)

**Comment by BILY5354** [comment]
Can I change the size of the fonts by modifying the configuration file, it's very useful for me, thank you!

**Comment by codecadwallader** [comment]
Unfortunately, we do not currently have configuration setup to change the font size.
