### ISSUE TITLE
Cleanup Progress window layout not correct

### ISSUE THREAD

**Issue by Hefaistos68** [codecadwallader/codemaid#801]
### Environment
- Visual Studio version: 2019 Community 16.9.3
- CodeMaid version: 11.2.231
- Code language: C#

### Description
Thats what I get on my system here when I do a complete cleanup:
![image](https://user-images.githubusercontent.com/8855055/114151622-33f52980-9915-11eb-8892-e34d66f730d9.png)

### Steps to recreate
Not sure this can be recreated without the same display and system settings, but hopefully the screenshot points in the right direction.

**Comment by Hefaistos68** [comment]
Just realized that this window is actually resizable, so its not an issue at all. Just the initial size is off.

**Comment by codecadwallader** [comment]
Out of curiosity, what OS are you using?  The dialog looks a bit different than Windows standard.

**Comment by Hefaistos68** [comment]
Windows 10 Home, although with UI animations disabled.

**Comment by digitaldirk** [comment]
I have also experienced this. Not a big deal at all, but it would just be a nice little update if more people are experiencing it @codecadwallader. Willing to test further if needed but I hope its easy for someone who is already setup to test this. 

### Environment:
- Windows 11 10.0.22000 Build 22000
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.1.6
- CodeMaid version 12.0
- My display resolution is 1600x900, 100% scale, default font size, no custom fonts.

### Information I found:
- When I screenshot the Cleanup Progress Window with Snipping Tool the dimensions of the picture is:  386x173
     ![DefaultWindow](https://user-images.githubusercontent.com/22691956/168903149-f251d705-e7aa-4384-87f2-7a9ab26ec13e.png)
- If I resize the window just barely (by just a pixel I believe because image is now 386x174) the text is not cutoff anymore:
     ![ResizedWindow](https://user-images.githubusercontent.com/22691956/168903428-545dcf81-ffc9-4189-bb41-b4b69918a13f.png)
- I see that in the xaml the window should be 400x180. I am not sure if my method of taking a screenshot is accurate or what happens when the window is being displayed - but **maybe a fix would be bumping up the height by 5 - or maybe adjusting the xaml layout slightly?** https://github.com/codecadwallader/codemaid/blob/7fb6ce85821c77c3de1a2e679138751347d82827/CodeMaidShared/UI/Dialogs/CleanupProgress/CleanupProgressWindow.xaml#L13


Please let me know if I can do anything else related to this, thank you.

**Comment by codecadwallader** [comment]
Thanks for the information @digitaldirk .  Makes sense to add a bit of padding.  I've added 10 pixels to this dialog as well as another similarly sized one in #929
