### ISSUE TITLE
Question:Any solution to run natively cleanup of visual studio with codemaid

### ISSUE THREAD

**Issue by Winches** [codecadwallader/codemaid#920]
### Environment
- Visual Studio version: [2022 Professional]
- CodeMaid version: [12.0]
- Code language: [C#]

### Description
Cleaning of codemaid is fine,but natively cleanup has lots of fixer which is useful.
It' will be lovely if codemaid can have this feature.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/7054776/162660351-bf05b22b-4041-425c-a0ca-e26c8fb6eb79.png">

**Comment by codecadwallader** [comment]
Thanks for asking the question.  I believe you can turn on automatic cleanup on save for Visual Studio's new cleanup functionality, similar to how CodeMaid works.  I found this setting under Tools->Options by searching for cleanup (screenshot).

![image](https://user-images.githubusercontent.com/3823772/166450161-422d6ffb-dd91-4674-b7bd-75dbd727091e.png)

It is possible this could cause conflicts with CodeMaid's cleanup since they're both trying to run on the save event.  The main thing to check is that CodeMaid still has its default options to skip undo transactions during automatic cleanup on save (screenshot).

![image](https://user-images.githubusercontent.com/3823772/166450390-8f9493c7-3bc8-44e5-8cd7-6ad5689ec977.png)

Hope it helps!

**Comment by Winches** [comment]
Thanks for your  suggestion.I'm using automatically cleanup now
