### ISSUE TITLE
Automatic Cleanup On Save... doesn't

### ISSUE THREAD

**Issue by jdx-john** [codecadwallader/codemaid#953]
### Environment
- Visual Studio version: 2022 Pro
- CodeMaid version: 12.0.3
- Code language: C#

### Description
I have checked "Automatic Cleanup On Save" in Extensions->CodeMaid options
![image](https://user-images.githubusercontent.com/1654627/196159575-7c7b7ad5-edd8-4283-8240-0229253586b9.png)

When I edit a file and save it, I see no evidence of CM making any changes. If I explicitly run code cleanup on the same file, changes _are_ made.
![image](https://user-images.githubusercontent.com/1654627/196159786-5d672637-67e2-4359-b64e-57f094c92eb4.png)

### Steps to recreate
Just one example with `using` but it seems to be a general problem.

1. Enable "Automatic Cleanup On Save"
2. Add a spurious `using` to a code file in your C# project (VS will show it as not needed)
3. Save the file - the using remains
4. Explicitly cleanup the file by right-clicking it in the solution explorer - the using is removed as expected

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Using statements are a special case that by default skip cleaning during automatic cleanup on save.  This is due to some possible conflicts where updating using statements during a save event could trigger an infinite loop depending on configuration and other installed extensions.

If you want to change this behavior, there is an option at CodeMaid->Options->Cleaning->Visual Studio->Run remove and sort using statements->Skip during automatic cleanup on save that controls it.

Hope it helps!

**Comment by jdx-john** [comment]
I confirm this works as you describe - thanks. As far as I am concerned I will close it, unless the team deems it worth further attention.
